#!/bin/bash
set -x

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$TM_USER" PASSWORD '$TM_PASSWORD' LOGIN SUPERUSER INHERIT NOREPLICATION;

    CREATE DATABASE "$TM_DB";

    ALTER DATABASE "$TM_DB" OWNER TO "$TM_USER";

    CREATE ROLE "as_ADMIN";

    GRANT CONNECT ON DATABASE "$TM_DB" TO "$TM_USER";

    GRANT "as_ADMIN" TO "$TM_USER";

EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$TM_DB" <<-EOSQL

        CREATE SCHEMA "$TM_SCHEMA" AUTHORIZATION "as_ADMIN";

        ALTER SCHEMA "$TM_SCHEMA" OWNER TO "$TM_USER";

        GRANT CREATE ON DATABASE "$TM_DB" TO "as_ADMIN";

        GRANT ALL PRIVILEGES ON SCHEMA "$TM_SCHEMA" TO "as_ADMIN";

        GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "$TM_SCHEMA" TO "as_ADMIN";

        GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "$TM_SCHEMA" TO "as_ADMIN";
EOSQL